materials:
  - name: "ABS"
    brand: "3D Fila"
    colors: []
    notes: []

  - name: "ASA"
    brand: "3D Fila"
    colors: []
    notes: []

  - name: "PET"
    brand: "3D Fila"
    colors: []
    notes: []
